theme = "boo_berry"

[editor]
cursorline = true

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
