shell = "zsh"

[plugins]

[plugins.zsh-syntax-highlighting]
git = "https://github.com/zsh-users/zsh-syntax-highlighting.git"

[plugins.zsh-autosuggestions]
git = "https://github.com/zsh-users/zsh-autosuggestions.git"
